### ISSUE TITLE
Is there a way to configure EventGridTrigger locally to use hybrid relay endpoint?

### ISSUE THREAD

**Issue by dawiduniec** [Azure/azure-functions-eventing-extension#102]
Hello,

I managed to configure console app to be triggered locally via hybrid connection, but I can't find anything in documentation regarding EventGridTrigger. Am I missing something?

**Comment by alrod** [comment]
@dawiduniec,
Can you please clarify "console app to be triggered locally via hybrid connection"
Doe this doc help https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-event-grid-trigger-local?

**Comment by alrod** [comment]
Closing as no response.
