### ISSUE TITLE
Event Grid not delivery storage blob create events to function app running in Azure

### ISSUE THREAD

**Issue by saikovvuri** [Azure/azure-functions-eventing-extension#103]
Hello, 

I have a storage account , Standard V2 LRS,  , I created a subscription from the "Events" and selected endpoint type as Azure Function and selected an eventgrid triggered azure function.  However when I try to upload new blob items,  the event grid topic is reporting delivery failures -  
**outcome=Unauthorized, latencyInMs=1727, state=FilteredFailingDelivery**

My function declaration is 
[FunctionName(nameof(ProcessOrderBlobEventClient))]
public async Task Run(
        [EventGridTrigger] EventGridEvent eventGridEvent,

<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>

Regards,
Sai

**Comment by msekkappan** [comment]
Sai
Did you find an answer?  I have similar issues, we have easy auth enabled in Azure function.
Thanks
Malathi
