### ISSUE TITLE
Support batched Event Grid Events

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-eventing-extension#71]
The programming model needs to have support for getting a collection of events as part of a single invocation.

```csharp
public static void EventGridTest([EventGridTrigger] EventGridEvent[] eventGridEvents, ILogger log)
{
    ...
}
```

Keep in mind that this needs to work for other languages as well. Semantics for checkpointing / responding to Grid about completion need to be all-or-none.

See the EventHub trigger as an example.

Scenario-wise, part of this is to handle high-throughput. I can see a scenario where this is combined with Durable Functions to process through the batch, having checkpointed the whole batch with grid but capturing it in Durable

**Comment by ankitkumarr** [comment]
For other languages to work with this, 
1. We can leverage the `cardinality` property in `function.json`. So, users would likely have to specify `"cardinality" : "many"` in their `function.json` for the collection of events to work.
2. The language workers (or libraries) would need to add support for converting data received by the host to the appropriate collection (for rich binding type).
