### ISSUE TITLE
Event Grid Messages "ABORTED".. Problem with Function or Event Grid?

### ISSUE THREAD

**Issue by krankin** [Azure/azure-functions-eventing-extension#78]
I have an Azure function (dedicated App service plan) triggered by an Event Grid message when a file is created in Azure Blob Storage. 

This seems to work very well in the small scale. However, when I add, say 1000 files to Azure Storage, it appears as if my Function isn't being triggered. 
Investigating in EventGrid shows that the majority of those errors have a "GenericError" and are "Aborted"..  

Looking at metrics for the Azure function, it doesn't appear that its hitting any kind of resource constraint (that I can tell). Memory/CPU/ all seem to be well below the capacity of my app service plan. 

As i can't seem to drill any deeper into what an "Aborted" message is, and searching the web hasn't turned up much. I'm looking for help figuring out how to diagnose if this problem is in the configuration of my Function or in how I'm trying to use Event grid?  

Thanks.

**Comment by krankin** [comment]
Closing this issue. Problem was not related to eventgrid.

**Comment by bhomer7** [comment]
I'm encountering a similar error involving EventGrid and delivering events to an App Service via a WebHook. What was your solution to the problem? What was the problem related to?

**Comment by krankin** [comment]
IIRC, my problem was in my azure function. I believe I was exhausting ports available for my function and events were being queued waiting for resources to the point that I eventually experienced timeouts. We resolved this by better resource management and scaling out our function.
