### ISSUE TITLE
Azure Functions broken for NetCore3.1 

### ISSUE THREAD

**Issue by chris-oswald** [Azure/azure-functions-eventing-extension#81]
I've upgraded to my Azure Function to netcoreapp3.1 targeting function v3.  Since this change my EventGridTrigger attribute wont bind.  It fails with:

System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'eventGridEvent'. Microsoft.Azure.WebJobs.Host: The method or operation is not implemented

Here are my dependencies:

```
<PackageReference Include="Microsoft.Azure.EventGrid" Version="3.2.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.1.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.2" />
```

If you start a new function from Scratch in VS2019 you can reproduce in just a few mintues on localhost with postman.

Side note: if I use webhooks with 3.1 everything works fine.  The only difference is the EventGrid extension.

**Comment by scp-mb** [comment]
Seeing a very similar issue on our end.

```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.4" />
  </ItemGroup>
```

With just the default scaffolded EventGridTrigger function results in the following error:

> The 'Function1' function is in error: The binding type(s) 'eventGridTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.

**Comment by brandonh-msft** [comment]
I have an event grid triggered function working perfectly on 3.1... can you provide a repro sample somewhere?

My csproj:
```xml
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6" />
```

my function def:
```csharp
        [FunctionName("clientDisconnected")]
        public static async Task RemoveClient(ILogger log,
            [EventGridTrigger]EventGridEvent[] disconnectedEvents,
```

Is it possible you're not accounting for the array'd nature of the binding object? [Event Grid events are _always_ broadcast in arrays](https://docs.microsoft.com/en-us/azure/event-grid/event-schema#event-schema), even if just an array of 1

**Comment by scp-mb** [comment]
Updating `Microsoft.NET.Sdk.Functions` from `3.0.4` to `3.0.6` seems to have resolved the issue. Binding to an array of `EventGridEvent` doesn't seem necessary (and wasn't in the past either). None of the documentation mentions you need to do that and suggests the function app will be automatically called once per array element.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=csharp

`The example shown is an array of one element. Event Grid always sends an array and may send more than one event in the array. The runtime invokes your function once for each array element.`

**Comment by brandonh-msft** [comment]
Glad you got it figured out.

#please-close

**Comment by alrod** [comment]
Closing as resolved.
