### ISSUE TITLE
We need to support the newer cloud event 

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-eventing-extension#84]
https://docs.microsoft.com/en-us/azure/event-grid/cloudevents-schema#cloudevent-schema

**Comment by jotatoledo** [comment]
hey, could anyone please provide some info about this feature current state?
Thanks in advance :)

**Comment by tomkerkhove** [comment]
Bump, any news on this? Would be good to be able to use an open standard.

For now I'll have to move to doing it ourselves to until this is supported...

**Comment by justinyoo** [comment]
Is it safe to assume that this extension supports CloudEvents, when the [new version of SDK](https://www.nuget.org/packages/Azure.Messaging.EventGrid) goes GA?

**Comment by alrod** [comment]
[New version](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/3.1.0) should support this. Closing.

**Comment by tomkerkhove** [comment]
Thank you!
