### ISSUE TITLE
Event Grid Trigger missing direction in function.json

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-functions-eventing-extension#86]
For a C# function using the Event Grid trigger, the generated function.json (/bin/Debug/netcoreapp3.1/MyTrigger/function.json) is missing the "direction" attribute.  

According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=javascript#configuration), the "direction" attribute with a value of "in" is required for an EventGridTrigger attribute.

The function.json file appears as follows:

```json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.3",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "eventGridTrigger",
      "name": "eventGridEvent"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/myfunction.dll",
  "entryPoint": "Company.Function.EventGridTriggerCSharp1.Run"
}
```

**Environment**
- VS Code: 1.47.0-insiders
- .NET Core: 3.1.301
- Azure CLI: 2.8.0
- Azure Functions Core Tools: 3.0.2630

**Comment by mathewc** [comment]
Related to https://github.com/Azure/azure-functions-vs-build-sdk/issues/426. Your function works correctly right - you're just asking why the direction isn't present?

**Comment by mcollier** [comment]
Correct. The function appears to work as expected.

**Comment by alrod** [comment]
Direction attribute is not specified for C# precompiled and function.json is generated automatically:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=csharp#binding-direction
